name: CI Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit pytest pylint isort flake8 bandit black mypy

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Run pytest
        run: pytest tests/ -v

      - name: Run pylint
        run: pylint src/ --rcfile=.pylintrc

      - name: Run mypy
        run: mypy src/ --config-file mypy.ini

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Deploy Application
        run: |
          echo "Deploy logic here"
